### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ericmil87** [vasani-arpit/Social-Media-Automation#1]
I'm using mac and raspberry, is it possible to run on these platforms?

**Comment by ericmil87** [comment]
Btw the projects sounds great! Well done!

**Comment by vasani-arpit** [comment]
Thank you!!

Thanks for asking. I think I should add this instructional into readme.md
Yes. you can run this in windows, Linux and in Mac. I am not sure about raspberry

How to run this

1) Clone the repo using `git clone`
2) cd into the dir
3) `npm install`
4) `npm start`

You will get an UI same as I have in that gif. As your read in readme.md this is not functional yet. It is yet to be written.

**Comment by ericmil87** [comment]
Alright!
Thank you for the quick reply!
